package view;

import dto.SystemFilter;

import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;

import entity.Product;
import entity.ProductUnit;
import entity.Supplier;
import service.SupplierService;
import service.impl.ProductServiceImpl;
import service.impl.SupplierServiceImpl;
import com.github.sarxos.webcam.Webcam;
import com.github.sarxos.webcam.WebcamPanel;
import com.github.sarxos.webcam.WebcamResolution;
import com.google.zxing.BinaryBitmap;
import com.google.zxing.LuminanceSource;
import com.google.zxing.MultiFormatReader;
import com.google.zxing.Result;
import com.google.zxing.client.j2se.BufferedImageLuminanceSource;
import com.google.zxing.common.HybridBinarizer;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.math.BigDecimal;
import java.math.RoundingMode;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.HashMap;
import java.util.Map;
import javax.swing.ImageIcon;
import javax.swing.JComboBox;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import service.impl.PurchaseOrderServiceImpl;

/**
 *
 * @author admin
 */
public class AddProductFrame extends javax.swing.JDialog {

    Product curProduct;
    ProductUnit curUnit;

    ProductServiceImpl productService = new ProductServiceImpl();
    PurchaseOrderServiceImpl purchaseOrderService = new PurchaseOrderServiceImpl();
    SupplierService supplierService = new SupplierServiceImpl();

    private javax.swing.table.DefaultTableModel orderTableModel;
    private final Map<Integer, PendingProductEntry> pendingProductEntries = new HashMap<>();

    private static class PendingProductEntry {

        int productId;
        String barcode;
        String productName;
        int quantity;
        public int ratio = 1;
        BigDecimal importPrice;
        BigDecimal sellingPrice;
        BigDecimal markupRate;
        String category;
        String baseUnit;
        String imageName;
    }

    // Constructor mặc định
    public AddProductFrame(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        initCustomComponents();
        initSupplierCombobox();
        initStatusCombobox();
    }

    private void initCustomComponents() {
        // 1. Khóa chặt ô Mã lô hàng
        txtBatchCode.setEditable(false);
        txtBatchCode.setText("Quét mã để tự sinh lô...");

        // 2. Khóa các trường danh mục cố định
        proTxt.setEditable(false);
        catTxt.setEditable(false);
        selllUnitTxt.setEditable(false);
        ratioTxt.setEditable(true);
        sellPriceTxt.setEditable(true);

        // Thay thế đoạn cấu hình bảng cũ thành đoạn này:
        String[] columns = {"Mã Barcode", "Tên Sản Phẩm", "Số Lượng", "Giá Nhập", "Thành Tiền",
            "imageMeta"};
        orderTableModel = new javax.swing.table.DefaultTableModel(columns, 0) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        tableOrderDetails.setModel(orderTableModel);
        if (tableOrderDetails.getColumnModel().getColumnCount() > 5) {
            javax.swing.table.TableColumn imageMetaColumn = tableOrderDetails.getColumnModel().getColumn(5);
            imageMetaColumn.setMinWidth(0);
            imageMetaColumn.setMaxWidth(0);
            imageMetaColumn.setPreferredWidth(0);
            imageMetaColumn.setResizable(false);
        }

        // Hiển thị tổng tiền ban đầu
        updateTotalAmountDisplay();

        barcodeTxt.addActionListener(evt -> triggerBarcodeSearch());
    }

    // FIX LỖI: Bổ sung hàm cập nhật hiển thị tổng tiền bị thiếu
    private void updateTotalAmountDisplay() {
        double totalSum = 0;
        int rowCount = orderTableModel.getRowCount();

        // Cột Thành Tiền nằm ở vị trí index số 6 (cột cuối cùng)
        for (int i = 0; i < rowCount; i++) {
            try {
                String totalCell = orderTableModel.getValueAt(i, 6).toString().replace(",", "");
                totalSum += Double.parseDouble(totalCell);
            } catch (Exception e) {
                // Tránh lỗi nếu định dạng số có vấn đề
            }
        }

        // Định dạng số có dấu phẩy phân cách hàng nghìn (Ví dụ: 3,250,000 VND)
        if (lblTotalOrderAmount != null) {
            lblTotalOrderAmount.setText(String.format(" %,.0f VND", totalSum));
        }
    }

    private void generateAutoBatchCode(int productId) {
        DateTimeFormatter dtf = DateTimeFormatter.ofPattern("yyyyMMdd-HHmmss");
        String timestamp = LocalDateTime.now().format(dtf);
        String autoGeneratedCode = "LOT-" + productId + "-" + timestamp;

        txtBatchCode.setText(autoGeneratedCode);
    }

    private void initSupplierCombobox() {
        ((JComboBox) cmbSupplier).removeAllItems();
        try {
            java.util.List<Supplier> suppliers = supplierService.getAllActiveSuppliers();
            for (Supplier supplier : suppliers) {
                ((javax.swing.JComboBox) cmbSupplier).addItem(supplier); // Hết sạch lỗi biên dịch!
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
        }
    }

    public AddProductFrame(java.awt.Frame parent, boolean modal, Product product, ProductUnit unit) {
        super(parent, modal);
        this.curProduct = product;
        this.curUnit = unit;
        initComponents();
        initCustomComponents();
        initSupplierCombobox();
        initStatusCombobox();
    }

    private void triggerBarcodeSearch() {
        String rawBarcode = safeText(barcodeTxt.getText());
        if (rawBarcode.isEmpty()) {
            return;
        }

        try {
            // Sử dụng chính hàm băm của hệ thống để chuyển đổi mã vạch thô sang mã DB
            String systemBarcode = util.ShortHash.ProductBarcodeHash(rawBarcode);

            clearProductFields();
            barcodeTxt.setText(rawBarcode);

            java.util.Optional<ProductUnit> unitOpt = productService.getUnitByBarcode(systemBarcode);

            if (unitOpt != null && unitOpt.isPresent()) {
                ProductUnit unit = unitOpt.get();
                java.util.Optional<Product> productOpt = productService.getProductById(unit.getProductId());

                if (productOpt != null && productOpt.isPresent()) {
                    Product product = productOpt.get();
                    this.curProduct = product;
                    this.curUnit = unit;

                    proTxt.setText(product.getProductName());
                    catTxt.setText(product.getCategory());
                    selllUnitTxt.setText(unit.getUnitName());
                    impUnitTxt.setText(unit.getUnitName());
                    ratioTxt.setText(String.valueOf(unit.getRatio()));
                    sellPriceTxt.setText(unit.getSellingPrice() != null ? unit.getSellingPrice().toString() : "0");
                    impPriceTxt.setText(product.getImportPrice() != null ? product.getImportPrice().toString() : "0");

                    proTxt.setEditable(false);
                    catTxt.setEditable(false);
                    selllUnitTxt.setEditable(false);

                    generateAutoBatchCode(product.getId());
                } else {
                    // Trả về logic gốc nếu không tìm thấy Product
                    Product newProduct = new Product();
                    newProduct.setId(0);
                    this.curProduct = newProduct;

                    proTxt.setText("");
                    catTxt.setText("");
                    selllUnitTxt.setText("");
                    impUnitTxt.setText("");
                    ratioTxt.setText("1");
                    sellPriceTxt.setText("0");
                    impPriceTxt.setText("0");
                    proTxt.setEditable(true);
                    catTxt.setEditable(true);
                    selllUnitTxt.setEditable(true);

                    generateAutoBatchCode(0);
                }
            } else {
                // Trả về logic gốc nếu không tìm thấy ProductUnit
                Product newProduct = new Product();
                newProduct.setId(0);
                this.curProduct = newProduct;

                proTxt.setText("");
                catTxt.setText("");
                selllUnitTxt.setText("");
                impUnitTxt.setText("");
                ratioTxt.setText("1");
                sellPriceTxt.setText("0");
                impPriceTxt.setText("0");
                proTxt.setEditable(true);
                catTxt.setEditable(true);
                selllUnitTxt.setEditable(true);

                generateAutoBatchCode(0);
            }

            if (impUnitTxt != null) {
                impUnitTxt.requestFocus();
            }
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi khi xử lý mã vạch: " + ex.getMessage(), "Lỗi",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    private String normalizeBarcode(String rawBarcode) {
        String barcode = safeText(rawBarcode);
        if (barcode.isEmpty()) {
            return "";
        }
        return barcode.toUpperCase().startsWith("PRO-") ? barcode.toUpperCase() : "PRO-" + barcode;
    }

    private void clearProductFields() {
        barcodeTxt.setText("");
        proTxt.setText("");
        catTxt.setText("");
        selllUnitTxt.setText("");
        ratioTxt.setText("1");
        sellPriceTxt.setText("0");
        impPriceTxt.setText("0");
        impUnitTxt.setText("");
        markupRateTxt.setText("0%");
        discountTxt1.setText("");
        cmbSupplier.setSelectedIndex(0);
        statusComboBox.setSelectedIndex(0);
        selectedImagePath = null;
        lblImagePreview.setIcon(null);
        proTxt.setEditable(false);
        catTxt.setEditable(false);
        selllUnitTxt.setEditable(false);
        ratioTxt.setEditable(true);
        sellPriceTxt.setEditable(true);
        curProduct = null;
        curUnit = null;
    }

    private static final java.util.logging.Logger logger = java.util.logging.Logger
            .getLogger(AddProductFrame.class.getName());

    /**
     * Creates new form AddProductFrame
     */
    public AddProductFrame() {
        initComponents();
        initCustomComponents();
        initSupplierCombobox();
        initStatusCombobox();

        javax.swing.event.DocumentListener autoCalculateListener = new javax.swing.event.DocumentListener() {
            @Override
            public void insertUpdate(javax.swing.event.DocumentEvent e) {
                calculateMarkup();
            }

            @Override
            public void removeUpdate(javax.swing.event.DocumentEvent e) {
                calculateMarkup();
            }

            @Override
            public void changedUpdate(javax.swing.event.DocumentEvent e) {
                calculateMarkup();
            }

            private void calculateMarkup() {
                try {
                    String impPriceStr = impPriceTxt.getText().trim();
                    String ratioStr = ratioTxt.getText().trim();
                    String sellPriceStr = sellPriceTxt.getText().trim();

                    // Kiểm tra xem người dùng đã điền đủ số liệu ở 3 ô cần thiết chưa
                    if (!impPriceStr.isEmpty() && !ratioStr.isEmpty() && !sellPriceStr.isEmpty()) {
                        java.math.BigDecimal importPrice = new java.math.BigDecimal(impPriceStr);
                        int ratio = Integer.parseInt(ratioStr);
                        java.math.BigDecimal sellingPricePerUnit = new java.math.BigDecimal(sellPriceStr);

                        // Chặn lỗi chia cho số 0
                        if (importPrice.compareTo(java.math.BigDecimal.ZERO) > 0 && ratio > 0) {
                            // Giá bán thùng = Giá bán lẻ * Tỉ lệ quy đổi
                            java.math.BigDecimal calculatedSellPricePerBox = sellingPricePerUnit
                                    .multiply(new java.math.BigDecimal(ratio));

                            // Tỉ Lệ Lãi = (Giá bán thùng - Giá nhập thùng) / Giá nhập thùng
                            java.math.BigDecimal markupRate = calculatedSellPricePerBox.subtract(importPrice)
                                    .divide(importPrice, 4, java.math.RoundingMode.HALF_UP);

                            // Đổi ra phần trăm (Ví dụ: 0.2000 -> 20)
                            java.math.BigDecimal displayMarkup = markupRate.multiply(new java.math.BigDecimal("100"));

                            // Gán text hiển thị lên Label kèm ký tự %
                            markupRateTxt.setText(String.format("%.0f%%", displayMarkup));
                        }
                    } else {
                        markupRateTxt.setText("0%");
                    }
                } catch (NumberFormatException ex) {
                    // Người dùng đang gõ dở hoặc nhập sai ký tự số, đưa nhãn về 0%
                    markupRateTxt.setText("0%");
                }
            }
        };

        impPriceTxt.getDocument().addDocumentListener(autoCalculateListener);
        ratioTxt.getDocument().addDocumentListener(autoCalculateListener);
        sellPriceTxt.getDocument().addDocumentListener(autoCalculateListener);

    }

    private void initStatusCombobox() {
        statusComboBox.removeAllItems();
        statusComboBox.setModel(new javax.swing.DefaultComboBoxModel(new SystemFilter[]{
            SystemFilter.ACTIVE,
            SystemFilter.INACTIVE
        }));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        statusComboBox = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        impUnitTxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        ratioTxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        sellPriceTxt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        barcodeTxt = new javax.swing.JTextField();
        discountTxt1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        markupRateTxt = new javax.swing.JLabel();
        proTxt = new javax.swing.JTextField();
        scanBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        selllUnitTxt = new javax.swing.JTextField();
        addImgBtn = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        catTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        impPriceTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblImagePreview = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        cmbSupplier = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        txtBatchCode = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        qtyTxt = new javax.swing.JTextField();
        panelOrderBottom = new javax.swing.JPanel();
        lblTotalOrderAmount1 = new javax.swing.JLabel();
        addProBtn = new javax.swing.JButton();
        lblTotalOrderAmount = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableOrderDetails = new javax.swing.JTable();
        addBtn = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Thêm nhập kho"));

        statusComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        statusComboBox.addActionListener(this::statusComboBoxActionPerformed);

        jLabel7.setText("Đơn Vị Khi Nhập:");

        jLabel8.setText("Tỉ Lệ Tính:");

        jLabel9.setText("Giá Bán:");

        jLabel10.setText("SALE *Nếu có:");

        jLabel1.setText("Tên Sản Phẩm:");

        markupRateTxt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        markupRateTxt.setForeground(new java.awt.Color(255, 0, 0));
        markupRateTxt.setText("0%");

        proTxt.addActionListener(this::proTxtActionPerformed);

        scanBtn.setText("Quét mã");
        scanBtn.addActionListener(this::scanBtnActionPerformed);

        jLabel2.setText("Đơn Vị Tính:");

        selllUnitTxt.addActionListener(this::selllUnitTxtActionPerformed);

        addImgBtn.setText("Thêm ảnh");
        addImgBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addImgBtnMouseClicked(evt);
            }
        });
        addImgBtn.addActionListener(this::addImgBtnActionPerformed);

        jLabel12.setText("Mã barcode:");

        jLabel3.setText("Loại Sản Phẩm:");

        jLabel4.setText("Giá Nhập:");

        jLabel5.setText("Tỉ Lệ Lãi:");

        jLabel6.setText("Trạng Thái:");

        jLabel13.setText("Nhà Cung Cấp:");

        cmbSupplier.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel14.setText("Mã Lô Hàng:");

        jLabel15.setText("Số lượng nhập:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel12)
                            .addComponent(jLabel4)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(selllUnitTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel14))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(impPriceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(catTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel10))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(proTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(75, 75, 75)
                                    .addComponent(jLabel8)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(impUnitTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel13)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtBatchCode, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(statusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cmbSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                                .addComponent(lblImagePreview, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(markupRateTxt))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(discountTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(addImgBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(ratioTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(71, 71, 71)
                                        .addComponent(jLabel9))
                                    .addComponent(jLabel15))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(qtyTxt)
                                    .addComponent(sellPriceTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE))))
                        .addContainerGap(12, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(barcodeTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(scanBtn)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(barcodeTxt)
                    .addComponent(scanBtn)
                    .addComponent(jLabel15)
                    .addComponent(qtyTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                        .addComponent(proTxt)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(ratioTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9)
                        .addComponent(sellPriceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(catTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel10)
                            .addComponent(discountTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(addImgBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(selllUnitTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14)
                            .addComponent(txtBatchCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(impPriceTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(statusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(cmbSupplier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(impUnitTxt))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblImagePreview, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(markupRateTxt))
                        .addGap(14, 14, 14))))
        );

        panelOrderBottom.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        lblTotalOrderAmount1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTotalOrderAmount1.setForeground(new java.awt.Color(255, 0, 0));
        lblTotalOrderAmount1.setText("Tổng tiền:");

        addProBtn.setText("Xác nhận");
        addProBtn.addActionListener(this::addProBtnActionPerformed);

        lblTotalOrderAmount.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblTotalOrderAmount.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout panelOrderBottomLayout = new javax.swing.GroupLayout(panelOrderBottom);
        panelOrderBottom.setLayout(panelOrderBottomLayout);
        panelOrderBottomLayout.setHorizontalGroup(
            panelOrderBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelOrderBottomLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(panelOrderBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addProBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelOrderBottomLayout.createSequentialGroup()
                        .addComponent(lblTotalOrderAmount1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTotalOrderAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelOrderBottomLayout.setVerticalGroup(
            panelOrderBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelOrderBottomLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelOrderBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalOrderAmount1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTotalOrderAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addProBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        tableOrderDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableOrderDetails);

        addBtn.setText("Thêm");
        addBtn.addActionListener(this::addBtnActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelOrderBottom, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addBtn, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(addBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(panelOrderBottom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void selllUnitTxtActionPerformed(java.awt.event.ActionEvent evt) {
        if (safeText(barcodeTxt.getText()).isEmpty()) {
            barcodeTxt.requestFocus();
            return;
        }

        triggerBarcodeSearch();
    }

    private void addProBtnActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            if (orderTableModel.getRowCount() == 0) {
                addCurrentEntryToTable();
            }

            savePendingEntries();
        } catch (IllegalArgumentException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Cảnh báo", JOptionPane.WARNING_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Lưu dữ liệu thất bại: " + ex.getMessage(), "Lỗi",
                    JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {
        try {
            addCurrentEntryToTable();
            clearProductFields();
            barcodeTxt.requestFocus();
        } catch (IllegalArgumentException ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Cảnh báo", JOptionPane.WARNING_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Không thể thêm dòng vào bảng: " + ex.getMessage(), "Lỗi",
                    JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }

    private void addCurrentEntryToTable() {
        PendingProductEntry entry = buildCurrentEntry();
        int rowIndex = orderTableModel.getRowCount();

        BigDecimal lineTotal = entry.importPrice.multiply(BigDecimal.valueOf(entry.quantity));
        orderTableModel.addRow(new Object[]{
            entry.barcode,
            entry.productName,
            String.format("%,d", entry.quantity),
            formatDecimal(entry.importPrice),
            formatDecimal(lineTotal),
            entry.imageName
        });
        pendingProductEntries.put(rowIndex, entry);
        updateTotalAmountDisplay();
    }

    private void savePendingEntries() {
        if (orderTableModel.getRowCount() == 0) {
            throw new IllegalArgumentException(
                    "Không có dữ liệu để lưu. Vui lòng thêm dòng hoặc nhập thông tin sản phẩm.");
        }

        try {
            Supplier selectedSupplier = (Supplier) cmbSupplier.getSelectedItem();
            if (selectedSupplier == null || selectedSupplier.getId() <= 0) {
                throw new IllegalArgumentException("Vui lòng chọn nhà cung cấp hợp lệ trước khi lưu đơn nhập.");
            }

            repository.StoreRepository storeRepo = new repository.StoreRepository();
            java.util.List<entity.Store> activeStores = storeRepo.findAllActive();
            if (activeStores.isEmpty()) {
                throw new IllegalStateException("Không tìm thấy cửa hàng hoạt động để tạo đơn nhập.");
            }

            BigDecimal totalAmount = BigDecimal.ZERO;
            for (int i = 0; i < orderTableModel.getRowCount(); i++) {
                PendingProductEntry entry = pendingProductEntries.get(i);
                if (entry == null) {
                    continue;
                }
                totalAmount = totalAmount.add(entry.importPrice.multiply(BigDecimal.valueOf(entry.quantity)));
            }

            entity.PurchaseOrder po = new entity.PurchaseOrder();
            po.setSupplierId(selectedSupplier.getId());
            po.setStoreId(activeStores.get(0).getId());
            po.setTotalAmount(totalAmount);
            po.setStatus("pending");

            try (java.sql.Connection conn = util.DatabaseUtil.getConnection()) {
                conn.setAutoCommit(false);

                try {
                    int newOrderId = purchaseOrderService.insert(po, conn);
                    if (newOrderId <= 0) {
                        throw new java.sql.SQLException("Tạo hóa đơn nhập hàng tổng thất bại.");
                    }

                    for (int i = 0; i < orderTableModel.getRowCount(); i++) {
                        PendingProductEntry entry = pendingProductEntries.get(i);
                        if (entry == null) {
                            continue;
                        }

                        purchaseOrderService.insertOrderDetailSmart(
                                newOrderId,
                                entry.productId,
                                entry.productName,
                                entry.barcode,
                                entry.quantity,
                                entry.importPrice,
                                entry.sellingPrice,
                                entry.markupRate,
                                entry.category,
                                entry.baseUnit,
                                conn);
                    }

                    conn.commit();

                    JOptionPane.showMessageDialog(this, "Lưu đơn nhập hàng thành công!", "Thông báo",
                            JOptionPane.INFORMATION_MESSAGE);

                    orderTableModel.setRowCount(0);
                    pendingProductEntries.clear();
                    updateTotalAmountDisplay();

                } catch (Exception ex) {
                    conn.rollback();
                    throw ex;
                }
            }

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Lên đơn nhập thất bại: " + ex.getMessage(), "Lỗi",
                    JOptionPane.ERROR_MESSAGE);
            ex.printStackTrace();
        }
    }

    private PendingProductEntry buildCurrentEntry() {
        String rawBarcode = barcodeTxt.getText().trim();
        String finalBarcode = rawBarcode.startsWith("PRO-") ? rawBarcode : "PRO-" + rawBarcode;
        String productName = safeText(proTxt.getText());

        // --- ÁNH XẠ CHUẨN XÁC THEO HỆ THỐNG BIẾN CỦA BẠN ---
        String quantityText = safeText(qtyTxt.getText());         // Số lượng nhập (qtyTxt) -> 50
        String ratioText = safeText(ratioTxt.getText());           // Tỉ lệ tính (ratioTxt) -> 100
        String importPriceText = safeText(impPriceTxt.getText());    // Giá nhập (impPriceTxt) -> 650,000
        String sellPriceText = safeText(sellPriceTxt.getText());      // Giá bán (sellPriceTxt)

        String category = safeText(selllUnitTxt.getText());       // Loại sản phẩm (sellUnitTxt) -> Sẽ ra "Đồ dùng học tập"
        String baseUnit = safeText(catTxt.getText());           // Đơn vị tính lẻ (catTxt) -> Sẽ ra "Chiếc"
        // ---------------------------------------------------

        if (finalBarcode.isEmpty()) {
            throw new IllegalArgumentException("Vui lòng quét hoặc nhập mã vạch!");
        }
        if (productName.isEmpty()) {
            throw new IllegalArgumentException("Vui lòng nhập hoặc quét mã để lấy Tên sản phẩm!");
        }
        if (category.isEmpty()) {
            throw new IllegalArgumentException("Vui lòng nhập Loại sản phẩm!");
        }
        if (baseUnit.isEmpty()) {
            throw new IllegalArgumentException("Vui lòng nhập Đơn vị tính lẻ!");
        }
        if (quantityText.isEmpty() || importPriceText.isEmpty()) {
            throw new IllegalArgumentException("Vui lòng nhập đầy đủ Số lượng nhập và Giá nhập!");
        }

        int quantity = Integer.parseInt(quantityText.replace(",", ""));
        if (quantity <= 0) {
            throw new IllegalArgumentException("Số lượng nhập phải lớn hơn 0!");
        }

        int ratio = ratioText.isEmpty() ? 1 : Integer.parseInt(ratioText.replace(",", ""));
        if (ratio <= 0) {
            throw new IllegalArgumentException("Tỉ lệ tính phải lớn hơn 0!");
        }

        BigDecimal importPrice = new BigDecimal(importPriceText.replace(",", ""));
        if (importPrice.compareTo(BigDecimal.ZERO) < 0) {
            throw new IllegalArgumentException("Giá nhập sản phẩm không được phép âm!");
        }

        PendingProductEntry entry = new PendingProductEntry();
        entry.productId = (this.curProduct != null && this.curProduct.getId() > 0) ? this.curProduct.getId() : 0;
        entry.barcode = finalBarcode;
        entry.productName = productName;
        entry.quantity = quantity;
        entry.ratio = ratio;
        entry.importPrice = importPrice.setScale(2, RoundingMode.HALF_UP);
        entry.sellingPrice = parseDecimalOrZero(sellPriceText);
        entry.markupRate = parseMarkupRateFromLabel();
        entry.category = category; // Đã lưu trúng "Nhóm hàng"
        entry.baseUnit = baseUnit; // Đã lưu trúng "Chiếc/Cây"
        entry.imageName = resolveCurrentImageName();
        return entry;
    }

    private BigDecimal parseMarkupRateFromLabel() {
        String rawRate = safeText(markupRateTxt.getText());
        if (rawRate.isEmpty() || "0%".equals(rawRate)) {
            return BigDecimal.ZERO;
        }

        try {
            String normalizedRate = rawRate.replace("%", "").trim();
            if (normalizedRate.isEmpty()) {
                return BigDecimal.ZERO;
            }
            BigDecimal rate = new BigDecimal(normalizedRate);
            if (rate.compareTo(BigDecimal.ZERO) < 0) {
                return BigDecimal.ZERO;
            }
            return rate.divide(BigDecimal.valueOf(100), 4, RoundingMode.HALF_UP);
        } catch (NumberFormatException ex) {
            return BigDecimal.ZERO;
        }
    }

    private BigDecimal calculateMarkupRate(BigDecimal importPrice, String sellPriceText, String ratioText) {
        if (importPrice == null || importPrice.compareTo(BigDecimal.ZERO) <= 0) {
            return BigDecimal.ZERO;
        }
        if (sellPriceText == null || sellPriceText.trim().isEmpty()) {
            return BigDecimal.ZERO;
        }

        try {
            int ratio = Integer.parseInt(ratioText.replace(",", ""));
            if (ratio <= 0) {
                return BigDecimal.ZERO;
            }

            BigDecimal sellingPricePerUnit = new BigDecimal(sellPriceText.replace(",", ""));
            if (sellingPricePerUnit.compareTo(BigDecimal.ZERO) <= 0) {
                return BigDecimal.ZERO;
            }

            BigDecimal calculatedSellPricePerBox = sellingPricePerUnit.multiply(BigDecimal.valueOf(ratio));
            return calculatedSellPricePerBox.subtract(importPrice)
                    .divide(importPrice, 4, RoundingMode.HALF_UP);
        } catch (NumberFormatException ex) {
            return BigDecimal.ZERO;
        }
    }

    private String formatDecimal(BigDecimal value) {
        if (value == null) {
            return String.format("%,.2f", BigDecimal.ZERO);
        }
        return String.format("%,.2f", value);
    }

    private String safeText(String value) {
        return value == null ? "" : value.trim();
    }

    private String resolveCurrentImageName() {
        if (selectedImagePath == null || selectedImagePath.isBlank()) {
            return "";
        }

        File imageFile = new File(selectedImagePath);
        return imageFile.getName().isBlank() ? "" : imageFile.getName();
    }

    private String resolveTableImageName(int rowIndex, String fallbackImageName) {
        try {
            Object value = orderTableModel.getValueAt(rowIndex, 7);
            String imageName = value == null ? "" : value.toString().trim();
            if (!imageName.isEmpty()) {
                return imageName;
            }
        } catch (Exception ignored) {
        }

        return fallbackImageName == null ? "" : fallbackImageName.trim();
    }

    private BigDecimal parseDecimalOrZero(String value) {
        String normalized = safeText(value);
        if (normalized.isEmpty()) {
            return BigDecimal.ZERO;
        }

        try {
            return new BigDecimal(normalized.replace(",", ""));
        } catch (NumberFormatException ex) {
            return BigDecimal.ZERO;
        }
    }

    private void clearEntryFields() {
        clearProductFields();
    }

    private void clearSavedEntries() {
        orderTableModel.setRowCount(0);
        pendingProductEntries.clear();
        updateTotalAmountDisplay();
        clearProductFields();
        barcodeTxt.requestFocus();
    }

    private void proTxtActionPerformed(java.awt.event.ActionEvent evt) {
        if (safeText(proTxt.getText()).isEmpty()) {
            proTxt.requestFocus();
            return;
        }

        catTxt.requestFocus();
    }

    private void statusComboBoxActionPerformed(java.awt.event.ActionEvent evt) {
        if (statusComboBox.getSelectedItem() == null) {
            return;
        }

        statusComboBox.requestFocus();
    }

    private void scanBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_scanBtnActionPerformed
        // 1. Khởi tạo Camera mặc định của máy tính
        Webcam webcam = Webcam.getDefault();
        if (webcam == null) {
            JOptionPane.showMessageDialog(this, "Không tìm thấy Camera/Webcam kết nối với máy tính!");
            return;
        }

        // Đặt độ phân giải cho Camera
        webcam.setViewSize(WebcamResolution.VGA.getSize());

        // Tạo một Panel hiển thị luồng hình ảnh của Camera
        WebcamPanel panel = new WebcamPanel(webcam);
        panel.setFPSDisplayed(true);
        panel.setDisplayDebugInfo(false);
        panel.setImageSizeDisplayed(false);
        panel.setMirrored(false);

        // 2. Tạo một cửa sổ JDialog nhỏ để hiện Camera lên màn hình
        JDialog scanDialog = new JDialog(this, "ĐANG QUÉT MÃ QUA CAMERA", true);
        scanDialog.add(panel);
        scanDialog.pack();
        scanDialog.setLocationRelativeTo(this);

        // 3. Tạo một Thread (luồng chạy ngầm) để chụp ảnh từ camera và phân tích mã
        // liên tục
        Thread scanThread = new Thread(() -> {
            try {
                while (webcam.isOpen()) {
                    BufferedImage image = webcam.getImage();
                    if (image != null) {
                        LuminanceSource source = new BufferedImageLuminanceSource(image);
                        BinaryBitmap bitmap = new BinaryBitmap(new HybridBinarizer(source));

                        try {
                            // Thư viện ZXing tiến hành đọc mã vạch từ ảnh
                            Result result = new MultiFormatReader().decode(bitmap);

                            if (result != null) {
                                String barcodeResult = result.getText().trim();

                                // Đọc thành công! Đẩy mã vạch vào ô TextBox trên Form chính
                                barcodeTxt.setText(barcodeResult);

                                // Phát tiếng beep và đóng camera, đóng cửa sổ quét
                                java.awt.Toolkit.getDefaultToolkit().beep();
                                webcam.close();
                                scanDialog.dispose();

                                SwingUtilities.invokeLater(() -> triggerBarcodeSearch());
                                break;
                            }
                        } catch (Exception e) {
                            // Cứ sau vài mili-giây nếu không tìm thấy mã vạch trong khung hình thì bỏ qua,
                            // quét tiếp khung hình sau
                        }
                    }
                    Thread.sleep(100); // Nghỉ 100ms trước khi quét hình tiếp theo để tránh treo máy
                }
            } catch (InterruptedException ex) {
                ex.printStackTrace();
            }
        });

        // Sự kiện nếu người dùng chủ động tắt cửa sổ Dialog quét đi thì phải tắt Camera
        // ngầm
        scanDialog.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                if (webcam.isOpen()) {
                    webcam.close();
                }
            }
        });

        // Kích hoạt luồng quét ngầm và mở cửa sổ Camera lên
        scanThread.start();
        scanDialog.setVisible(true);
    }

    private void addImgBtnMouseClicked(java.awt.event.MouseEvent evt) {
    }

    private String selectedImagePath = null;

    private void addImgBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_addImgBtnActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        // Chỉ cho phép chọn file ảnh
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Hình ảnh", "jpg", "png", "jpeg");
        fileChooser.setFileFilter(filter);

        int result = fileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            selectedImagePath = selectedFile.getAbsolutePath(); // Lưu đường dẫn tạm

            // Hiển thị ảnh lên Label (Cần viết hàm scale ảnh cho vừa vặn Label)
            ImageIcon icon = new ImageIcon(selectedImagePath);
            Image img = icon.getImage().getScaledInstance(lblImagePreview.getWidth(), lblImagePreview.getHeight(),
                    Image.SCALE_SMOOTH);
            lblImagePreview.setIcon(new ImageIcon(img));
        }
    }// GEN-LAST:event_addImgBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        java.awt.EventQueue.invokeLater(() -> new AddProductFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JButton addImgBtn;
    private javax.swing.JButton addProBtn;
    private javax.swing.JTextField barcodeTxt;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField catTxt;
    private javax.swing.JComboBox<String> cmbSupplier;
    private javax.swing.JTextField discountTxt1;
    private javax.swing.JTextField impPriceTxt;
    private javax.swing.JTextField impUnitTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblImagePreview;
    private javax.swing.JLabel lblTotalOrderAmount;
    private javax.swing.JLabel lblTotalOrderAmount1;
    private javax.swing.JLabel markupRateTxt;
    private javax.swing.JPanel panelOrderBottom;
    private javax.swing.JTextField proTxt;
    private javax.swing.JTextField qtyTxt;
    private javax.swing.JTextField ratioTxt;
    private javax.swing.JButton scanBtn;
    private javax.swing.JTextField sellPriceTxt;
    private javax.swing.JTextField selllUnitTxt;
    private javax.swing.JComboBox<String> statusComboBox;
    private javax.swing.JTable tableOrderDetails;
    private javax.swing.JTextField txtBatchCode;
    // End of variables declaration//GEN-END:variables
}
