/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import entity.Employee;
import entity.Store;

import java.math.BigDecimal;
import java.security.Timestamp;
import java.sql.Date;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import repository.EmployeeRepository;
import repository.StoreRepository;
import service.EmployeeService;
import service.impl.EmployeeServiceImpl;

/**
 *
 * @author admin
 */
public class EmployeeListFrame extends javax.swing.JFrame {

    EmployeeServiceImpl empSvc = new EmployeeServiceImpl();

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EmployeeListFrame.class.getName());

    /**
     * Creates new form EmployeeListFrame
     */
    public void LoadEmpTableData() {
        DefaultTableModel EmpTableModel = new DefaultTableModel(){
            //Khóa sửa trực tiếp trong cell 
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        EmployeeTable1.setModel(EmpTableModel);//Gán model cho table
        EmpTableModel.setColumnIdentifiers(new Object[]{"Id", "Họ Và Tên", "Ngày Tháng Năm Sinh", "Giới tính", "Số CMND", "Barcode", "Số Điện Thoại", "Email", "Địa Chỉ", "Làm Tại", "Lương Theo Giờ","Trạng Thái","Store_id"});
        EmpTableModel.setRowCount(0);
        try {
            List<Employee> EmpList = empSvc.getAllEmployees();
            // Thay thế store name thay vì store id
            StoreRepository storeRepo = new StoreRepository();
            List<Store> storeList = storeRepo.findAll();
            for (Employee employee : EmpList) {
                String storeName = storeList.stream()
                        .filter(store -> store.getId() == employee.getStoreId())
                        .findFirst()
                        .map(Store::getStoreName)
                        .orElse("Không xác định");
                EmpTableModel.addRow(new Object[]{employee.getId(), employee.getFullName(), employee.getBirthday(), employee.getGender(), employee.getIdCard(), employee.getEmployeeBarcode(), employee.getPhone(), employee.getEmail(), employee.getAddress(), storeName, employee.getHourlyRate(), employee.getStatus(), employee.getStoreId()});
            }
            // Ẩn cột id
            EmployeeTable1.getColumnModel().getColumn(12).setWidth(0);
            EmployeeTable1.getColumnModel().getColumn(12).setMaxWidth(0);
            EmployeeTable1.getColumnModel().getColumn(12).setMinWidth(0);
            EmployeeTable1.getColumnModel().getColumn(12).setPreferredWidth(0);
            EmployeeTable1.getColumnModel().getColumn(12).setResizable(false);
            EmployeeTable1.getColumnModel().getColumn(12).setResizable(false);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Lỗi khi tải dữ liệu nhân viên", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }

    }

    public EmployeeListFrame() {
        initComponents();

        LoadEmpTableData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        EmployeeTable1 = new javax.swing.JTable();
        EditEmpBtn = new javax.swing.JButton();
        RefreshButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        EmployeeTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(EmployeeTable1);

        EditEmpBtn.setText("Sửa Thông TIn Nhân Viên ");
        EditEmpBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditEmpBtnMouseClicked(evt);
            }
        });
        EditEmpBtn.addActionListener(this::EditEmpBtnActionPerformed);

        RefreshButton.setText("Làm Mới");
        RefreshButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RefreshButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(EditEmpBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(RefreshButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(EditEmpBtn)
                .addGap(18, 18, 18)
                .addComponent(RefreshButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void EditEmpBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditEmpBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EditEmpBtnActionPerformed

    private void RefreshButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RefreshButtonMouseClicked
        LoadEmpTableData();

    }//GEN-LAST:event_RefreshButtonMouseClicked

    private void EditEmpBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditEmpBtnMouseClicked
        int selectedrow = EmployeeTable1.getSelectedRow();
        if(selectedrow != -1){
            int id = (int) EmployeeTable1.getValueAt(selectedrow, 0);
            String fullName = (String) EmployeeTable1.getValueAt(selectedrow, 1);
            Date birthday = (Date) EmployeeTable1.getValueAt(selectedrow, 2);
            String gender = (String) EmployeeTable1.getValueAt(selectedrow, 3);
            String idCard = (String) EmployeeTable1.getValueAt(selectedrow, 4);
            String employeeBarcode = (String) EmployeeTable1.getValueAt(selectedrow, 5);
            String phone = (String) EmployeeTable1.getValueAt(selectedrow, 6);
            String email = (String) EmployeeTable1.getValueAt(selectedrow, 7);
            String address = (String) EmployeeTable1.getValueAt(selectedrow, 8);
            //Cast về store_id trước khi truyền 
            //Lấy store_id từ cột 12
            int storeId = (int) EmployeeTable1.getValueAt(selectedrow, 12);
            BigDecimal hourlyRate = (BigDecimal) EmployeeTable1.getValueAt(selectedrow, 10);
            String status = (String) EmployeeTable1.getValueAt(selectedrow, 11);
            Employee emp = new Employee(id, fullName, birthday, gender, idCard, employeeBarcode, phone, email, address, storeId, hourlyRate, status, null, null, false, null);
            AddEmpDialog updateEmp =  new AddEmpDialog(this, true, emp);
            updateEmp.setVisible(true);
            LoadEmpTableData();
        }else{
            JOptionPane.showMessageDialog(rootPane, "Vui lòng chọn 1 hàng");
        }
    }//GEN-LAST:event_EditEmpBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new EmployeeListFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EditEmpBtn;
    private javax.swing.JTable EmployeeTable1;
    private javax.swing.JButton RefreshButton;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
