package view;

import java.sql.SQLException;
import javax.swing.DefaultButtonModel;
import javax.swing.JOptionPane;
import service.AuthService;
import service.impl.AuthServiceImpl;
import util.ClientInfoUtil;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author admin
 */
public class LoginFrame extends javax.swing.JFrame {

    AuthServiceImpl authImpl = new AuthServiceImpl();
    // public boolean isPasswordBlank(char[] password) {
    // for (char c : password) {
    // if (!Character.isWhitespace(c)) {
    // return false;
    // }
    // }
    // return !(password == null || password.length == 0);
    // }
    private static final java.util.logging.Logger logger = java.util.logging.Logger
            .getLogger(LoginFrame.class.getName());

    /**
     * Creates new form LoginDialog
     */
    public LoginFrame() {
        initComponents();
        DefaultButtonModel btn = (DefaultButtonModel) loginButton.getModel();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        userNameTextFeild = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        loginButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 720));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Login");

        userNameTextFeild.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        userNameTextFeild.setPreferredSize(new java.awt.Dimension(200, 30));
        userNameTextFeild.setRequestFocusEnabled(false);
        userNameTextFeild.setVerifyInputWhenFocusTarget(false);
        userNameTextFeild.addActionListener(this::userNameTextFeildActionPerformed);

        passwordField.setPreferredSize(new java.awt.Dimension(200, 30));
        passwordField.addActionListener(this::passwordFieldActionPerformed);

        jLabel2.setText("UserName");

        jLabel3.setText("Password");

        loginButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        loginButton.setText("Login");
        loginButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginButtonMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(135, 135, 135)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel2)
                                        .addComponent(jLabel3))
                                .addGap(54, 54, 54)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(userNameTextFeild, javax.swing.GroupLayout.PREFERRED_SIZE, 197,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 187,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(196, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(loginButton)
                                .addGap(262, 262, 262)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(76, 76, 76)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(userNameTextFeild, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2))
                                .addGap(38, 38, 38)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(passwordField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3))
                                .addGap(63, 63, 63)
                                .addComponent(loginButton)
                                .addContainerGap(117, Short.MAX_VALUE)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userNameTextFeildActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_userNameTextFeildActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_userNameTextFeildActionPerformed

    private void passwordFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_passwordFieldActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_passwordFieldActionPerformed

    private void loginButtonMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_loginButtonMouseClicked
        String username = userNameTextFeild.getText();
        String password = new String(passwordField.getPassword());
        if (username.isBlank() || password.isBlank()) {
            JOptionPane.showMessageDialog(null, "Tên người dùng và mật khẩu không được để trống", "",
                    JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                String ip = ClientInfoUtil.getClientIP();
                String ua = ClientInfoUtil.getClientUserAgent();

                // 1. Thử đăng nhập với vai trò Admin trước
                AuthService.LoginResponse adminResponse = authImpl.loginAdmin(username, password, ip, ua);

                if (adminResponse != null) {

                    JOptionPane.showMessageDialog(rootPane, "Đăng nhập thành công với quyền Admin!");

                    //
                    //
                    //
                    this.dispose();

                } else {
                    // 2. Nếu không phải Admin, thử tiếp với vai trò Manager
                    AuthService.LoginResponse managerResponse = authImpl.loginManager(username, password, ip, ua);

                    if (managerResponse != null) {
                        JOptionPane.showMessageDialog(rootPane, "Đăng nhập thành công với quyền Manager!");

                        //
                        //
                        //
                        this.dispose();

                    } else {
                        // 3. Cả 2 đều trả về null nghĩa là sai tài khoản/mật khẩu
                        JOptionPane.showMessageDialog(rootPane, "Tên đăng nhập hoặc mật khẩu không chính xác",
                                "Đăng nhập thất bại", JOptionPane.ERROR_MESSAGE);
                    }
                }

            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(rootPane, "Lỗi kết nối cơ sở dữ liệu!", "Lỗi hệ thống",
                        JOptionPane.ERROR_MESSAGE);
                System.getLogger(LoginFrame.class.getName()).log(System.Logger.Level.ERROR, (String) null, ex);
            }

        }
    }// GEN-LAST:event_loginButtonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new LoginFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton loginButton;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JTextField userNameTextFeild;
    // End of variables declaration//GEN-END:variables
}
