package view;

import entity.Invoice;
import entity.InvoiceDetail;
import entity.ProductUnit;
import service.InvoiceService;
import service.impl.InvoiceServiceImpl;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;
import repository.EmployeeRepository;
import repository.ProductUnitRepository;
import repository.StoreRepository;

public class POSFrame extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(POSFrame.class.getName());

    private final InvoiceService invoiceService = new InvoiceServiceImpl();
    private final List<InvoiceDetail> cartList = new ArrayList<>();
    private final ProductUnitRepository productUnitRepo = new ProductUnitRepository();
    private final StoreRepository storeRepo = new StoreRepository();
    private final EmployeeRepository employeeRepo = new EmployeeRepository();
    private BigDecimal totalInvoiceAmount = BigDecimal.ZERO;

    public POSFrame() {
        setTitle("HỆ THỐNG BÁN HÀNG TẠI QUẦY - POS");
        initComponents();
        this.pack();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new java.awt.Panel();
        jLabel1 = new javax.swing.JLabel();
        txtStoreBarcode = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtBarcode = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtEmployeeBarcode = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableCart = new javax.swing.JTable();
        panelBottom = new java.awt.Panel();
        lblTotalAmount = new javax.swing.JLabel();
        btnCheckout = new javax.swing.JButton();

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Mã Cửa Hàng:");

        jLabel2.setText("Mã Nhân Viên");

        jLabel3.setText("Mã Vạch Sản Phẩm:");

        jLabel4.setText("Số Lượng Mua:");

        btnAdd.setText("Thêm hàng");
        btnAdd.addActionListener(this::btnAddActionPerformed);

        tableCart.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tableCart);

        lblTotalAmount.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lblTotalAmount.setText("Tổng tiền:");

        javax.swing.GroupLayout panelBottomLayout = new javax.swing.GroupLayout(panelBottom);
        panelBottom.setLayout(panelBottomLayout);
        panelBottomLayout.setHorizontalGroup(
            panelBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBottomLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTotalAmount, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelBottomLayout.setVerticalGroup(
            panelBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBottomLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTotalAmount)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnCheckout.setText("Thanh toán");
        btnCheckout.addActionListener(this::btnCheckoutActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtStoreBarcode, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(67, 67, 67)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtEmployeeBarcode, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel4)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtBarcode, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                        .addComponent(btnAdd)))
                .addGap(21, 21, 21))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelBottom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(btnCheckout, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtStoreBarcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(txtBarcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtEmployeeBarcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelBottom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCheckout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(131, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCheckoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckoutActionPerformed
        if (cartList.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Giỏ hàng hiện tại đang trống!", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String storeCode = txtStoreBarcode.getText().trim();
        String empBarcode = txtEmployeeBarcode.getText().trim();

        if (storeCode.isEmpty() || empBarcode.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ Mã Cửa Hàng và Mã Nhân Viên!", "Thiếu thông tin", JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Khóa nút tạm thời để chống nhân viên "click đúp" tạo 2 hóa đơn trùng nhau
        btnCheckout.setEnabled(false);

        try {
            // 1. DỊCH MÃ: Lấy ID dạng số nguyên (int) từ các mã vạch đầu vào
            // (Thay thế bằng hàm gọi Service/Repo thực tế của bạn)
            int realStoreId = storeRepo.findIdByCode(storeCode)
                    .orElseThrow(() -> new RuntimeException("Mã Cửa Hàng '" + storeCode + "' không tồn tại!"));

            int realEmployeeId = employeeRepo.findIdByBarcode(empBarcode)
                    .orElseThrow(() -> new RuntimeException("Mã Nhân Viên '" + empBarcode + "' không hợp lệ!"));

            // 2. CHẠY TRANSCATION: Đẩy xuống tầng service bẻ lô xả kho
            Invoice completedInvoice = invoiceService.createInvoice(realStoreId, realEmployeeId, cartList);

            // Nếu không có exception nào ném ra -> Transaction tự động COMMIT thành công!
            JOptionPane.showMessageDialog(this,
                    "Thanh toán thành công!\nHóa đơn số: " + completedInvoice.getId()
                    + "\nSố kho đã được khấu trừ tự động theo niên hạn lô hàng (FEFO)!",
                    "Thành công", JOptionPane.INFORMATION_MESSAGE);

            // 3. Làm sạch giao diện để đón khách tiếp theo
            cartList.clear();
            ((DefaultTableModel) tableCart.getModel()).setRowCount(0);
            totalInvoiceAmount = BigDecimal.ZERO;
            lblTotalAmount.setText("Tổng tiền: 0 VND");

        } catch (Exception ex) {
            // Nếu dính lỗi thiếu hàng ở một lô bất kỳ -> Hệ thống đã ROLLBACK toàn cục an toàn
            JOptionPane.showMessageDialog(this,
                    "GIAO DỊCH THẤT BẠI - HỆ THỐNG ĐÃ HOÀN TÁC (ROLLBACK) KHO BÃI!\nChi tiết: " + ex.getMessage(),
                    "Lỗi Xuất Kho", JOptionPane.ERROR_MESSAGE);
        } finally {
            // Mở lại nút bấm
            btnCheckout.setEnabled(true);
        }
    }//GEN-LAST:event_btnCheckoutActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        String barcode = txtBarcode.getText().trim();
        String qtyStr = txtQuantity.getText().trim();

        if (barcode.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng quét hoặc nhập mã vạch sản phẩm!", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
            txtBarcode.requestFocus();
            return;
        }

        try {
            int quantity = Integer.parseInt(qtyStr);
            if (quantity <= 0) {
                JOptionPane.showMessageDialog(this, "Số lượng mua phải lớn hơn 0!", "Lỗi nhập liệu", JOptionPane.WARNING_MESSAGE);
                return;
            }

            // 2. Gọi Service/Repo để dịch mã vạch sang thực thể ProductUnit
            // Lưu ý: Đổi tên biến productUnitRepo theo đúng class bạn đã khai báo trong dự án
            Optional<ProductUnit> unitOpt = productUnitRepo.findByBarcode(barcode);

            if (!unitOpt.isPresent()) {
                JOptionPane.showMessageDialog(this, "Không tìm thấy sản phẩm nào khớp với mã vạch này!", "Lỗi hệ thống", JOptionPane.ERROR_MESSAGE);
                return;
            }

            ProductUnit unit = unitOpt.get();
            BigDecimal price = unit.getSellingPrice();
            BigDecimal subtotal = price.multiply(BigDecimal.valueOf(quantity));

            // 3. Đóng gói thông tin nạp vào giỏ hàng ẩn (RAM) để chuẩn bị thanh toán
            InvoiceDetail detail = new InvoiceDetail();
            detail.setProductId(unit.getProductId());
            detail.setUnitId(unit.getId()); // ID đơn vị tính
            detail.setQuantity(quantity);
            detail.setPriceAtSale(price);
            detail.setSubtotal(subtotal);
            cartList.add(detail);

            // 4. Đẩy dữ liệu hiển thị trực quan lên bảng JTable
            // (Khớp với 5 cột: Mã Vạch, Tên/ID, Số Lượng, Đơn Giá, Thành Tiền)
            DefaultTableModel model = (DefaultTableModel) tableCart.getModel();
            model.addRow(new Object[]{
                unit.getBarcode(),
                "Sản phẩm ID: " + unit.getProductId() + " (" + unit.getUnitName() + ")",
                quantity,
                price + " đ",
                subtotal + " đ"
            });

            // 5. Cập nhật lại nhãn hiển thị Tổng tiền dưới chân trang
            totalInvoiceAmount = totalInvoiceAmount.add(subtotal);
            lblTotalAmount.setText("Tổng tiền: " + totalInvoiceAmount + " VND");

            // 6. Reset nhanh ô nhập để chờ lượt quét tiếp theo
            txtBarcode.setText("");
            txtQuantity.setText("1");
            txtBarcode.requestFocus();

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Số lượng mua bắt buộc phải là số nguyên!", "Lỗi định dạng", JOptionPane.ERROR_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Lỗi truy vấn: " + ex.getMessage(), "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        SwingUtilities.invokeLater(() -> new POSFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnCheckout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTotalAmount;
    private java.awt.Panel panel1;
    private java.awt.Panel panelBottom;
    private javax.swing.JTable tableCart;
    private javax.swing.JTextField txtBarcode;
    private javax.swing.JTextField txtEmployeeBarcode;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtStoreBarcode;
    // End of variables declaration//GEN-END:variables
}
